// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-XoehEuvp5FkpH-NbOwxKaUJyAOl5Jg',
    appId: '1:867865938969:web:e69f0c8d6ccd2e6178ae88',
    messagingSenderId: '867865938969',
    projectId: 'gopark-5fb62',
    authDomain: 'gopark-5fb62.firebaseapp.com',
    storageBucket: 'gopark-5fb62.appspot.com',
    measurementId: 'G-YDYX9LFB2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9R7CX902rOg9KVegm2nR3-d68yQu6nbw',
    appId: '1:867865938969:android:ced8f9ec73748ef978ae88',
    messagingSenderId: '867865938969',
    projectId: 'gopark-5fb62',
    storageBucket: 'gopark-5fb62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7dDisbyFoNNXsB3j3WLktA45HFrgcOpQ',
    appId: '1:867865938969:ios:e326dc366d20ceff78ae88',
    messagingSenderId: '867865938969',
    projectId: 'gopark-5fb62',
    storageBucket: 'gopark-5fb62.appspot.com',
    iosClientId: '867865938969-fh8endcctal8drf7ee9af4kck2kaabk2.apps.googleusercontent.com',
    iosBundleId: 'com.inreks.goparkApp',
  );
}
